esa/nanosat-mo-framework

core/helper-tools/src/main/java/esa/mo/helpertools/helpers/HelperMisc.java, core/mo-services-impl/nmf-software-management-impl/src/main/java/esa/mo/sm/impl/provider/AppsLauncherManager.java, core/mo-services-impl/nmf-software-management-impl/src/main/java/esa/mo/sm/impl/provider/AppsLauncherProviderServiceImpl.java, core/mo-services-impl/nmf-software-management-impl/src/main/java/esa/mo/sm/impl/util/ClosingAppListener.java, sdk/tools/consumer-test-tool/src/main/java/esa/mo/nmf/ctt/services/sm/AppsLauncherConsumerPanel.java, sdk/tools/consumer-test-tool/src/main/java/esa/mo/nmf/ctt/services/sm/AppsLauncherTablePanel.java
This PR addresses the following issues:
* Bug #330: Supervisor should not execute experiments as root
* Bug #531: Stop app handling is not implemented for native and mixed apps
**Goal:** By default, apps are launched as the currently logged in user, i.e. root on the satellite. The new implementation should launch apps by their respective user on the satellite.
**Implementation:** The AppsLauncherManager now checks for a user property in provider.properties and uses its value to set the runAs value of the corresponding AppDetails. This field is populated by the package script of https://github.com/esa/nmf-mission-ops-sat. If the user property is not existent the AppsLauncherManager assumes an SDK environment and executes the app as the current user. Taking the app name as a default does …
=> Apps launcher improvement

core/mo-services-impl/nmf-platform-generic-impl/src/main/java/esa/mo/platform/impl/provider/gen/GPSNMEAonlyAdapter.java, core/mo-services-impl/nmf-platform-generic-impl/src/main/java/esa/mo/platform/impl/util/HelperGPS.java
the UTC field of the Position Object was set to null, instead of being parsed from the GPS message.
Its Implemented now.
=> FIX: UTC = null in Position from getPosition

core/mo-services-impl/ccsds-com-impl/src/main/java/esa/mo/com/impl/util/ObjectInstanceIdGenerator.java, core/mo-services-impl/ccsds-com-impl/src/test/java/esa/nmf/test/RegressionTest.java, core/mo-services-impl/ccsds-com-impl/src/test/java/esa/nmf/test/UniqueIDTest.java, core/nmf-composites/ground-mo-adapter/src/main/java/esa/mo/nmf/groundmoadapter/GroundMOAdapterImpl.java, core/nmf-composites/ground-mo-adapter/src/main/java/esa/mo/nmf/groundmoadapter/SimpleCommandingInterface.java
Adds a Method to create Unique action-instance IDs,
also changed the return statement of invokeAction to Long to be able to return the instance ID
=> [GroundMOAdapterImpl] Make action-instance-ID unique

core/mo-services-impl/nmf-platform-generic-impl/src/main/java/esa/mo/platform/impl/provider/gen/GPSProviderServiceImpl.java, mission/simulator/opssat-spacecraft-simulator/src/main/java/opssat/simulator/orekit/OrekitCore.java, mission/simulator/opssat-spacecraft-simulator/src/main/java/opssat/simulator/threading/SimulatorNode.java
Fixes error which occurred when calling get TLE while Orekit propagator was disabled. Now returns a default TLE (all Positional values zero)
=> [Simulator] Fix TLE error when Orekit propagator is deactivated

docs/source/sdk.rst
This fixes a small typo in the documentation for [getting started with the SDK](https://nanosat-mo-framework.readthedocs.io/en/latest/sdk.html).
**Before:**
**After:**
Note: The text above was only highlighted to denote the change, when taking the screenshots. It's not part of the pull request.
=> docs/source/sdk: s/apps our ground/apps and ground/

core/mo-services-impl/ccsds-com-impl/src/main/java/esa/mo/com/impl/sync/EncodeDecode.java
@CesarCoelho could you please confirm?
When parsing the COM archive file that @dmarszk provided me with my new tool:
- I found that the domain in the `COM`  `ObjectKey` of the `ObjectId` in `ObjectDetails` objects, was wrongly formatted as follow:
- `"[esa, nanosat-mo-supervisor]"` instead of `["esa", "nanosat-mo-supervisor"]`
- Considering that when you decode [here](https://github.com/esa/nanosat-mo-framework/blob/f761a58ec3c42fe46bd8836db2b64399849366c5/core/mo-services-impl/ccsds-com-impl/src/main/java/esa/mo/com/impl/sync/EncodeDecode.java#L211) you use the reversed function, I believe we need this fix
=> fix: archive sync domain encoding used wrong format

core/nmf-composites/nanosat-mo-supervisor/src/main/java/esa/mo/nmf/nanosatmosupervisor/MCSupervisorBasicAdapter.java, core/nmf-composites/nanosat-mo-supervisor/src/main/java/esa/mo/nmf/nanosatmosupervisor/parameter/OBSWParameter.java, core/nmf-composites/nanosat-mo-supervisor/src/main/java/esa/mo/nmf/nanosatmosupervisor/parameter/OBSWParameterManager.java, core/nmf-composites/nanosat-mo-supervisor/src/main/java/esa/mo/nmf/nanosatmosupervisor/parameter/ParameterLister.java, mission/simulator/opssat-spacecraft-simulator/src/main/java/opssat/simulator/threading/SimulatorNode.java
When loading parameters from xml, avoid loading the
whole file into memory by using the SAX parser instead.
In simulator, instead of reading file lines into array,
process them on the go.
=> Bug #1067 [supervisor] Reduce memory usage

sdk/tools/consumer-test-tool/src/main/java/esa/mo/nmf/ctt/services/mc/AggregationConsumerPanel.java, sdk/tools/consumer-test-tool/src/main/java/esa/mo/nmf/ctt/services/mc/ParameterPublishedValues.java, sdk/tools/consumer-test-tool/src/main/java/esa/mo/nmf/ctt/services/mc/StatisticConsumerPanel.java, sdk/tools/consumer-test-tool/src/main/java/esa/mo/nmf/ctt/services/sm/AppsLauncherConsumerPanel.java
CTT Panels subscribe to some parameters by default,
when tab is closed, deregister these subscriptions.
=> Bug #985 Deregister subscriptions

mission/simulator/opssat-spacecraft-simulator/src/main/java/opssat/simulator/threading/SimulatorNode.java, mission/simulator/platform-services-impl/src/test/java/esa/nmf/test/GPSSoftSimAdapterTest.java
TIMEA log format in simulator has been fixed.
- clock status field after the header was missing
(after the ';' separator, a "VALID" tag is expected).
- utc ms field should be a Ulong (range 0-60999) and not
a float (last value before the final "VALID" tag")
New unit test added to confirm the format.
=> Bug #1158 Wrong GPS TIMEA log format in simulator

mission/simulator/opssat-spacecraft-simulator/src/main/java/opssat/simulator/threading/SimulatorNode.java, mission/simulator/opssat-spacecraft-simulator/src/main/java/opssat/simulator/util/SimulatorData.java, mission/simulator/platform-services-impl/src/test/java/esa/nmf/test/GPSSoftSimAdapterTest.java
Bug #1157 Wrong GPS time in simulator GNSS logs
UTC and GPS difference should be 18seconds.
This should be reported in the relevant message field UTC-offset.
Both times in the TIMEA logs should be aligned to the "simulated" time
not the system time.
Based on the #1158 change.
=> Bug #1157 Wrong GPS time in simulator GNSS logs

mission/simulator/opssat-spacecraft-simulator/src/main/java/opssat/simulator/util/SimulatorData.java, mission/simulator/platform-services-impl/src/test/java/esa/nmf/test/GPSSoftSimAdapterTest.java
Improve the unit tests - make them more universal, following the OEM manual.
Fix the time formats in simulator - 12H format was used instead of 24H.
=> Bug #1158 [sim] Wrong GNSS log format

core/helper-tools/src/main/java/esa/mo/helpertools/misc/Const.java, core/mo-services-impl/nmf-platform-generic-impl/pom.xml, core/mo-services-impl/nmf-platform-generic-impl/src/main/java/esa/mo/platform/impl/provider/gen/GPSAdapterInterface.java, core/mo-services-impl/nmf-platform-generic-impl/src/main/java/esa/mo/platform/impl/provider/gen/GPSProviderServiceImpl.java, core/mo-services-impl/nmf-platform-generic-impl/src/main/java/esa/mo/platform/impl/util/HelperGPS.java, core/mo-services-xml/src/main/resources/xml/ServiceDefPLATFORM.xml, mission/simulator/opssat-spacecraft-simulator/src/main/java/opssat/simulator/orekit/OrekitCore.java, mission/simulator/opssat-spacecraft-simulator/src/main/java/opssat/simulator/util/SimulatorData.java, mission/simulator/platform-services-impl/src/main/java/esa/mo/platform/impl/provider/softsim/GPSSoftSimAdapter.java, mission/simulator/platform-services-impl/src/test/java/esa/nmf/test/GPSSoftSimAdapterTest.java, sdk/sdk-package/src/main/resources/space-supervisor-root/provider.properties
Option to use TLE propagation instead when GPS device
is unavailable. Also when GPS receiver is powered on,
but has no valid lock.
=> Issue #1077 [GPS] Provide simulated GPS data onboard

mission/simulator/platform-services-impl/src/main/java/esa/mo/platform/impl/provider/softsim/AutonomousADCSSoftSimAdapter.java, mission/simulator/platform-services-impl/src/main/java/esa/mo/platform/impl/provider/softsim/CameraSoftSimAdapter.java, mission/simulator/platform-services-impl/src/main/java/esa/mo/platform/impl/provider/softsim/GPSSoftSimAdapter.java, mission/simulator/platform-services-impl/src/main/java/esa/mo/platform/impl/provider/softsim/OpticalDataReceiverSoftSimAdapter.java, mission/simulator/platform-services-impl/src/main/java/esa/mo/platform/impl/provider/softsim/PowerControlSoftSimAdapter.java, mission/simulator/platform-services-impl/src/main/java/esa/mo/platform/impl/provider/softsim/SimulatorAdapter.java, mission/simulator/platform-services-impl/src/main/java/esa/mo/platform/impl/provider/softsim/SoftwareDefinedRadioSoftSimAdapter.java, mission/simulator/platform-services-impl/src/main/java/esa/mo/platform/impl/util/PlatformServicesProviderSoftSim.java, mission/simulator/platform-services-impl/src/test/java/esa/nmf/test/GPSSoftSimAdapterTest.java, mission/simulator/platform-services-impl/src/test/java/esa/nmf/test/RegressionTest0.java
Initialization of SoftSim adapters in hybrid
mode ended in error, so a common SimulatorAdapter
interface has been added to differentiate between
mission and simulator adapters.
Also removed the unused ESAsimulator variable from
PowerControlSoftSimAdapter.
=> Issue #1168 [simulator] SoftSim adapters

core/nmf-package-lib/src/main/java/esa/mo/nmf/nmfpackage/NMFPackageManager.java
Issue #1191 [package-manager] Fix path traversal write by Zip Slip vulnerability
https://gitlab.com/esa/NMF/nmf-issues/-/issues/1191
Fix the method generateFilePathForSystem() so the generated
path cannot go above the experimenter's folder
=> Issue #1191 [package-manager] Fix path traversal write by Zip Slip vulnerability

core/mo-services-impl/nmf-platform-generic-impl/src/main/java/esa/mo/platform/impl/provider/gen/GPSProviderServiceImpl.java
[GPS Provider Service] Change propagated TLE latitude units to degrees
Fix method getTLEPropagatedPosition() so that it
returns Position latitude in degrees like it does with 
longitude and altitude
=> [GPS Provider Service] Change propagated TLE latitude units to degrees

sdk/tools/com-archive-tool/src/main/java/esa/mo/nmf/comarchivetool/ArchiveBrowserHelper.java, sdk/tools/com-archive-tool/src/main/java/esa/mo/nmf/comarchivetool/adapters/ArchiveToAggreationsAdapter.java, sdk/tools/com-archive-tool/src/main/java/esa/mo/nmf/comarchivetool/adapters/ArchiveToParametersAdapter.java, sdk/tools/com-archive-tool/src/main/java/esa/mo/nmf/comarchivetool/commands/logs/LogsCommandsImplementations.java, sdk/tools/com-archive-tool/src/main/java/esa/mo/nmf/comarchivetool/commands/parameters/ParametersCommandsDefinitions.java, sdk/tools/com-archive-tool/src/main/java/esa/mo/nmf/comarchivetool/commands/parameters/ParametersCommandsImplementations.java
It is now possible to filter parameters based on the domain. There are some changes to how the commands should be called. Both `parameter list` and `parameter get` commands now require provider name as a parameter. Some examples:
Get all parameters from the LWMCS archive:
`parameter get -r maltcp://127.0.0.1:61617/LWMCS_Core-Directory parameters.log "App: LWMCS_Core"`
Providing "App: LWMCS_Core" as a provider name causes the tool to download parameters from the LWMCS archive containing all synchronized parameters. It is also possible to get parameters for a specific provider by providing a domain filter:
`parameter get -r maltcp://127.0.0.1:61617/LWMCS_Core-Directory -d some.provider.domain parameters.log "App: LWMCS_Core"`
There's also an option to get latest parameters directly from a …
=> Issue #1189 COM Archive Tool - support parameters from multiple domains

mission/simulator/opssat-spacecraft-simulator/src/main/java/opssat/simulator/threading/SimulatorNode.java
Change reloadImageBuffer() method
to be case insensitive to file extentions
Solved by: Pablo Ghiglino
email: pablo.ghiglino@klepsydra.com
=> [Camera Simulator] Make accepted file extentions case insensitive

core/nmf-composites/generic-composite-model/src/main/java/esa/mo/nmf/MonitorAndControlNMFAdapter.java, core/nmf-composites/nanosat-mo-supervisor/src/main/java/esa/mo/nmf/nanosatmosupervisor/MCSupervisorBasicAdapter.java, core/nmf-composites/nanosat-mo-supervisor/src/main/java/esa/mo/nmf/nanosatmosupervisor/parameter/DummyValuesProvider.java, core/nmf-composites/nanosat-mo-supervisor/src/main/java/esa/mo/nmf/nanosatmosupervisor/parameter/OBSWParameterManager.java, core/nmf-composites/nanosat-mo-supervisor/src/main/java/esa/mo/nmf/nanosatmosupervisor/parameter/OBSWParameterValuesProvider.java
…on selected OBSW parameters
https://gitlab.com/esa/NMF/nmf-issues/-/issues/1192
Add onSetValue method in OBSWParameterManager and
OBSWParameterValuesProvider symmetrical to the onGetValue.
Update the DummyValuesProvider to accept setValue calls.
Add temporary map that stores parameters/values after
setValue calls.
Update the DummyValuesProvider to return the entries upon
calling getValue method.
Update MonitorAndControlNMFAdapter to always return false
for OBSW parameter isReadOnly() checks.
Refactor onSetValue in MonitorAndControlNMFAdapter.
=> Issue #1192 [OBSW Parameter Manager] Allow Parameter::setValue calls

core/mo-services-impl/ccsds-com-impl/src/main/java/esa/mo/com/impl/provider/ArchiveSyncProviderServiceImpl.java
This pull request contains changes preventing null pointer exception from being thrown during first synchronization.
=> Issue #1202 - Fix random null pointer exception in archive sync at startup

sdk/tools/com-archive-tool/src/main/java/esa/mo/nmf/comarchivetool/ArchiveBrowserHelper.java, sdk/tools/com-archive-tool/src/main/java/esa/mo/nmf/comarchivetool/COMArchiveTool.java, sdk/tools/com-archive-tool/src/main/java/esa/mo/nmf/comarchivetool/adapters/ArchiveToBackupAdapter.java, sdk/tools/com-archive-tool/src/main/java/esa/mo/nmf/comarchivetool/commands/archive/ArchiveCommandsDefinitions.java, sdk/tools/com-archive-tool/src/main/java/esa/mo/nmf/comarchivetool/commands/archive/ArchiveCommandsImplementations.java
This pull request adds a new command `backup_and_clean` to the COM Archive Tool allowing to backup and delete data from a provider.
Example usage:
`com-archive-tool backup_and_clean -r maltcp://127.0.0.1:61617/LWMCS_Core-Archive -p "App: LWMCS_Core" test.provider.domain`
This will save all the data from the test.provider.domain domain into the file `test.provider.domain__yyyy-MM-dd__HH-mm-ss.db` and delete the data from the provider archive if the save was succesfull.
=> Issue #1201 Backup provider command in COM Archive Tool

core/nmf-composites/generic-composite-model/src/main/java/esa/mo/nmf/MonitorAndControlNMFAdapter.java, core/nmf-composites/generic-composite-model/src/main/java/esa/mo/nmf/annotations/Parameter.java, core/nmf-composites/nanosat-mo-connector/src/main/java/esa/mo/nmf/nanosatmoconnector/NanoSatMOConnectorImpl.java, docs/source/cli-tool.rst, docs/source/index.rst, sdk/examples/space/payloads-test/src/main/java/esa/mo/nmf/apps/PayloadsTestApp.java, sdk/examples/space/payloads-test/src/main/java/esa/mo/nmf/apps/PayloadsTestMCAdapter.java, sdk/tools/cli-tool/pom.xml, sdk/tools/cli-tool/src/main/java/esa/mo/nmf/clitool/BaseCommand.java
This pull request contains changes for issues 1185, 325 and fixes/improvements that were discussed during LWMCS/NMF CCN2 final presentation.
Changes in this pull request:
Issue 1185:
- new parameter `eclipsed` derived from supervisor parameters
- new aggregation with CADC0884, CADC0886, CADC0888, CADC0890, CADC0892, CADC0894
- more iADCS parameters exposed: 
- attitude quaternion
- angular velocity
- sun vector
- state target
- magnetorquers dipole moment
- magnetorquers state
- new aggregation with all iADCS parameters
- new parameter `supervisorTMPollingEnabled`  - when true specified parameters will be polled from the supervisor and their values will be printed to stdout. The parameters are loaded from the `esa.mo.nanosatmoframework.proxy.supervisor.parameters` property.
- 3 new …
=> Issue 1185 and 325
