core/mo-services-impl/ccsds-com-impl/src/main/java/esa/mo/com/impl/archive/db/DatabaseBackend.java
core/mo-services-impl/ccsds-com-impl/src/main/java/esa/mo/com/impl/archive/db/TransactionsProcessor.java
core/mo-services-impl/ccsds-com-impl/src/main/java/esa/mo/com/impl/provider/ArchiveManager.java
core/mo-services-impl/ccsds-com-impl/src/main/java/esa/mo/com/impl/provider/ArchiveProviderServiceImpl.java
core/mo-services-impl/ccsds-com-impl/src/main/java/esa/mo/com/impl/provider/ArchiveSyncProviderServiceImpl.java
core/mo-services-impl/ccsds-com-impl/src/main/java/esa/mo/com/impl/sync/ToDelete.java
core/mo-services-impl/ccsds-com-impl/src/main/java/esa/mo/com/impl/util/COMServicesProvider.java
core/mo-services-impl/ccsds-com-impl/src/main/java/esa/mo/com/impl/util/Quota.java
core/mo-services-impl/nmf-software-management-impl/src/main/java/esa/mo/sm/impl/provider/AppsLauncherProviderServiceImpl.java
core/nmf-composites/generic-nanosat-mo-supervisor/src/main/java/esa/mo/nmf/nanosatmosupervisor/NanoSatMOSupervisor.java
sdk/sdk-package/src/main/resources/space-supervisor-root/provider.properties

This PR addresses the following issues:
* Bug #523: Propose and implement COM Archive data persistence/rotation policy for space apps
* Bug #524: Save application's console output in the Supervisor's archive
Remarks to the implementation of #523: After finishing ArchiveSync, the ArchiveSync provider queries the archive and deletes all instances of ParameterValue and AggregationValue.

Apps launcher

---

core/mo-services-impl/ccsds-mc-impl/src/main/java/esa/mo/mc/impl/interfaces/ParameterStatusListener.java
core/mo-services-impl/ccsds-mc-impl/src/main/java/esa/mo/mc/impl/provider/ParameterManager.java
core/nmf-composites/generic-composite-model/src/main/java/esa/mo/nmf/MonitorAndControlNMFAdapter.java
core/nmf-composites/generic-composite-model/src/main/java/esa/mo/nmf/annotations/Action.java
core/nmf-composites/generic-composite-model/src/main/java/esa/mo/nmf/annotations/ActionParameter.java
core/nmf-composites/generic-composite-model/src/main/java/esa/mo/nmf/annotations/Aggregation.java
core/nmf-composites/generic-composite-model/src/main/java/esa/mo/nmf/annotations/Aggregations.java
core/nmf-composites/generic-composite-model/src/main/java/esa/mo/nmf/annotations/Parameter.java
core/nmf-composites/generic-composite-model/src/test/java/esa/nmf/test/ParameterTest.java
core/nmf-composites/generic-composite-model/src/test/java/esa/nmf/test/RegressionTest.java
sdk/examples/space/payloads-test/src/main/java/esa/mo/nmf/apps/PayloadsTestActionsHandler.java
sdk/examples/space/payloads-test/src/main/java/esa/mo/nmf/apps/PayloadsTestMCAdapter.java

Adds the possibility of using Java Annotations for:
Actions (@Action for Method) with parameters (@ActionParameter)
Aggregations (@Aggregation for class)
Parameters (@Parameter for field)
Implementations without Annotations are NOT effected by this.
Hybrid Implementations are possible.
(See PayloadsTestMCAddapter.java for example)

Mc provider annotations

---

docs/source/apps/actions.rst
docs/source/apps/main.rst
docs/source/apps/parameters.rst
docs/source/index.rst
docs/source/netbeans.rst
docs/source/opssat/testing.rst
docs/source/sdk.rst
docs/source/simulator/configure.rst

I went through `docs/source` and found some typos. I've resolved them via this PR, in case helpful.

[docs] Review for typos

---

core/helper-tools/src/main/java/esa/mo/helpertools/helpers/HelperMisc.java
core/mo-services-impl/nmf-platform-generic-impl/src/main/java/esa/mo/platform/impl/provider/gen/GPSNMEAonlyAdapter.java
core/mo-services-impl/nmf-platform-generic-impl/src/main/java/esa/mo/platform/impl/provider/gen/GPSProviderServiceImpl.java
core/mo-services-impl/nmf-software-management-impl/src/main/java/esa/mo/sm/impl/provider/AppsLauncherProviderServiceImpl.java
sdk/sdk-package/src/main/resources/space-common/settings.properties

fixes some problems related to gps polling and makes the polling rate configurable.

Gps polling configuration

---

core/mo-services-xml/src/main/resources/xml/ServiceDefPLATFORM.xml
docs/source/apps/apps.rst
sdk/examples/ground/camera-acquisitor-system-ground/pom.xml
sdk/examples/ground/camera-acquisitor-system-ground/src/main/java/esa/mo/ground/cameraacquisotorground/SpringInitiator.java
sdk/examples/ground/camera-acquisitor-system-ground/src/main/java/esa/mo/ground/restservice/Pass.java
sdk/examples/space/camera-acquisitor-system/pom.xml
sdk/examples/space/camera-acquisitor-system/src/main/java/esa/mo/nmf/apps/CameraAcquisitorSystemCameraHandler.java
sdk/examples/space/camera-acquisitor-system/src/main/java/esa/mo/nmf/apps/CameraAcquisitorSystemCameraTargetHandler.java
sdk/examples/space/camera-acquisitor-system/src/main/java/esa/mo/nmf/apps/CameraAcquisitorSystemGPSHandler.java
sdk/examples/space/camera-acquisitor-system/src/main/java/esa/mo/nmf/apps/CameraAcquisitorSystemMCAdapter.java
sdk/examples/space/payloads-test/src/main/java/esa/mo/nmf/apps/PayloadsTestCameraDataHandler.java
sdk/examples/space/payloads-test/src/main/java/esa/mo/nmf/apps/PayloadsTestMCAdapter.java

Camera acquisitor system

---

core/mo-services-impl/nmf-platform-generic-impl/src/main/java/esa/mo/platform/impl/provider/gen/AutonomousADCSAdapterInterface.java
core/mo-services-impl/nmf-platform-generic-impl/src/main/java/esa/mo/platform/impl/provider/gen/AutonomousADCSProviderServiceImpl.java
core/mo-services-xml/src/main/resources/xml/ServiceDefPLATFORM.xml
mission/simulator/platform-services-impl/src/main/java/esa/mo/platform/impl/provider/softsim/AutonomousADCSSoftSimAdapter.java

exposes some low level adcs functionality (currently without simulator implementation)

Low level adcs

---

core/mo-services-impl/nmf-software-management-impl/src/main/java/esa/mo/sm/impl/provider/AppsLauncherManager.java

Add missing file extension to make stop_exp runnable.

Bug #925 [apps-launcher] Fix stop script not getting executed

---

README.md

Small change to point the referential link mentioning this repository in the README, directly to this repository.

README: Update GitHub link to point directly to this repo

---

mission/simulator/opssat-spacecraft-simulator/src/main/java/opssat/simulator/gui/SFTPBrowser.java
mission/simulator/opssat-spacecraft-simulator/src/main/java/opssat/simulator/gui/SFTPInformation.java

Resolves #35.
@CesarCoelho Heya! I'm not sure if this was the correct license (I looked at the neighboring files in the same folder and copy/pasted). If it should be a different license, please let me know and I'll update my commit.

src/main/java/opssat/simulator/gui: Add license

---

docs/source/sdk.rst

+ s/playgrund/playground/
+ s/ordet/order/

docs/source/sdk.rst: Fix typos

---

core/mo-services-impl/ccsds-com-impl/src/main/java/esa/mo/com/impl/provider/ArchiveSyncProviderServiceImpl.java

Change allowing to configure the chunk size (esa.nmf.archive.sync.chunk.size) and poll timeout (esa.nmf.archive.sync.queue.poll.timeout).

Chunk size  and poll timeout 

---

sdk/examples/ground/set-and-command/pom.xml

Make the artifactId match the module.

Fix set-and-command artifactId

---

core/mo-services-impl/ccsds-com-impl/src/main/java/esa/mo/com/impl/archive/encoding/BinaryDecoder.java
core/mo-services-impl/ccsds-com-impl/src/main/java/esa/mo/com/impl/archive/encoding/GENEncoder.java
core/nmf-composites/generic-composite-model/src/main/java/esa/mo/nmf/NMFProvider.java
core/nmf-package-lib/src/main/java/esa/mo/nmf/nmfpackage/descriptor/NMFPackageDescriptor.java

* Manual array copy
* Use primitives
* Use StringBuilder loop
* Use Bulk Operations
* Use StandarCharset

Minor Performances Improvement:

---

core/helper-tools/src/main/java/esa/mo/helpertools/connections/ServicesConnectionDetails.java
core/helper-tools/src/main/java/esa/mo/helpertools/misc/ConsumerServiceImpl.java
core/helper-tools/src/main/java/esa/mo/helpertools/misc/TaskScheduler.java
core/helper-tools/src/test/java/esa/mo/helpertools/test/connections/TestServicesConnectionDetails.java
core/helper-tools/src/test/java/esa/mo/helpertools/test/helpers/TestHelperAttributes.java
core/misc/mal-elements-window/src/main/java/esa/mo/tools/mowindow/FieldsHandler.java
core/misc/mal-elements-window/src/main/java/esa/mo/tools/mowindow/MOWindow.java
core/misc/mal-elements-window/src/main/java/esa/mo/tools/mowindow/MOcomposite.java
core/misc/mal-elements-window/src/main/java/esa/mo/tools/mowindow/MOelement.java
core/misc/mal-elements-window/src/main/java/esa/mo/tools/mowindow/MOelementList.java
sdk/examples/ground/echo/src/main/java/esa/mo/ground/echo/AlertTest2.java
sdk/examples/space/benchmark/src/main/java/esa/mo/nmf/apps/StoreAggregations.java
sdk/examples/space/benchmark/src/main/java/esa/mo/nmf/apps/StoreParameters.java
sdk/examples/space/camera-acquisitor-system/src/main/java/esa/mo/nmf/apps/CameraAcquisitorSystemCameraTargetHandler.java
sdk/examples/space/camera/src/main/java/esa/mo/nmf/apps/MCSnapNMFAdapter.java
sdk/examples/space/gps/src/main/java/esa/mo/nmf/apps/DemoGPSData.java
sdk/examples/space/payloads-test/src/main/java/esa/mo/nmf/apps/PayloadsTestMCAdapter.java
sdk/tools/consumer-test-tool/src/main/java/esa/mo/nmf/ctt/guis/ConsumerTestToolGUI.java
sdk/tools/consumer-test-tool/src/main/java/esa/mo/nmf/ctt/services/com/ArchiveConsumerManagerPanel.java
sdk/tools/consumer-test-tool/src/main/java/esa/mo/nmf/ctt/services/com/ArchiveSyncConsumerManagerPanel.java
sdk/tools/consumer-test-tool/src/main/java/esa/mo/nmf/ctt/services/mc/ActionConsumerPanel.java
sdk/tools/consumer-test-tool/src/main/java/esa/mo/nmf/ctt/services/mc/AggregationConsumerPanel.java
sdk/tools/consumer-test-tool/src/main/java/esa/mo/nmf/ctt/services/sm/CommandExecutorConsumerPanel.java
sdk/tools/consumer-test-tool/src/main/java/esa/mo/nmf/ctt/utils/COMObjectWindow.java
sdk/tools/consumer-test-tool/src/main/java/esa/mo/nmf/ctt/utils/CommunicationsTopPanel.java
sdk/tools/consumer-test-tool/src/main/java/esa/mo/nmf/ctt/utils/SharedTablePanel.java

* Use Comparator combinator
* Replace Lambda with method reference
* Collapse identical try catch

Java 8 improvements

---

core/misc/image-debayer/pom.xml
core/misc/image-debayer/src/main/java/esa/opssat/camera/processing/OPSSATCameraDebayering.java
core/misc/image-debayer/src/main/java/ij/Debayer_Image.java
core/misc/image-debayer/src/main/java/ij/plugin/RGBStackConverterOpt.java
sdk/sdk-package/antpkg/build.xml

This resolves https://gitlab.com/esa/NMF/nmf-issues/-/issues/1132

Issue #1132 [Memory] Resolve camera provider memory issues

---

core/helper-tools/src/main/java/esa/mo/helpertools/misc/AppShutdownGuard.java
core/helper-tools/src/main/java/esa/mo/helpertools/misc/Const.java
core/nmf-composites/generic-nanosat-monolithic/src/main/java/esa/mo/nmf/nanosatmomonolithic/NanoSatMOMonolithic.java
core/nmf-composites/nanosat-mo-connector/src/main/java/esa/mo/nmf/nanosatmoconnector/NanoSatMOConnectorImpl.java
core/nmf-composites/nanosat-mo-supervisor/src/main/java/esa/mo/nmf/nanosatmosupervisor/NanoSatMOSupervisor.java

https://gitlab.com/esa/NMF/nmf-issues/-/issues/1130
This will protect the applications from hanging indefinitely
in their close handlers.

Issue #1130 [nmf-composites] Add application shutdown guard

---

core/mo-services-impl/nmf-platform-generic-impl/pom.xml
core/mo-services-impl/nmf-platform-generic-impl/src/main/java/esa/mo/platform/impl/util/HelperGPS.java
core/mo-services-impl/nmf-platform-generic-impl/src/test/java/esa/nmf/test/HelperGPSTest.java
core/mo-services-impl/nmf-platform-generic-impl/src/test/java/esa/nmf/test/RegressionTest0.java
core/mo-services-impl/nmf-platform-generic-impl/src/test/java/esa/nmf/test/RegressionTest1.java
core/mo-services-impl/nmf-platform-generic-impl/src/test/java/esa/nmf/test/RegressionTest2.java
core/mo-services-xml/src/main/resources/xml/ServiceDefPLATFORM.xml
mission/simulator/opssat-spacecraft-simulator/src/main/java/opssat/simulator/peripherals/PGPS.java

https://gitlab.com/esa/NMF/nmf-issues/-/issues/1125

Issue #1125 [GPS] Fix NMEA parser for position and satellite data

---

core/mo-services-impl/ccsds-com-impl/src/main/java/META-INF/persistence.xml
core/mo-services-impl/ccsds-com-impl/src/main/java/esa/mo/com/impl/archive/db/TransactionsProcessor.java
core/mo-services-impl/ccsds-com-impl/src/main/java/esa/mo/com/impl/consumer/ArchiveSyncConsumerServiceImpl.java
core/mo-services-impl/ccsds-com-impl/src/main/java/esa/mo/com/impl/provider/ArchiveManager.java
core/mo-services-impl/ccsds-com-impl/src/main/java/esa/mo/com/impl/provider/ArchiveSyncProviderServiceImpl.java
core/mo-services-impl/ccsds-com-impl/src/main/java/esa/mo/com/impl/sync/EncodeDecode.java
core/mo-services-impl/ccsds-mc-impl/src/main/java/esa/mo/mc/impl/provider/AggregationProviderServiceImpl.java
core/mo-services-impl/ccsds-mc-impl/src/main/java/esa/mo/mc/impl/provider/ParameterManager.java
core/mo-services-impl/ccsds-mc-impl/src/main/java/esa/mo/mc/impl/provider/ParameterProviderServiceImpl.java
core/mo-services-impl/ccsds-mc-impl/src/main/java/esa/mo/mc/impl/util/MCServicesHelper.java
core/mo-services-impl/nmf-software-management-impl/src/main/java/esa/mo/sm/impl/provider/AppsLauncherProviderServiceImpl.java

Contains fixes for issues 633, 1069, 1074, 1128, 1135, 1142

Issues 633, 1069, 1074, 1128, 1135, 1142

---

core/mo-services-impl/ccsds-com-impl/src/main/java/META-INF/persistence.xml
core/mo-services-impl/ccsds-com-impl/src/main/java/esa/mo/com/impl/archive/db/DatabaseBackend.java
core/mo-services-impl/ccsds-com-impl/src/main/java/esa/mo/com/impl/archive/entities/LastArchiveSyncEntity.java
core/mo-services-impl/ccsds-com-impl/src/main/java/esa/mo/com/impl/provider/ArchiveProviderServiceImpl.java
core/mo-services-impl/ccsds-com-impl/src/main/java/esa/mo/com/impl/provider/ArchiveSyncProviderServiceImpl.java
core/mo-services-impl/ccsds-com-impl/src/main/java/esa/mo/com/impl/sync/EncodeDecode.java

Issue 1150 fix

---

core/helper-tools/src/main/java/esa/mo/helpertools/misc/Const.java
core/nmf-composites/nmf-mo-adapters/space-mo-adapter/src/main/java/esa/mo/nmf/spacemoadapter/SpaceMOApdapterImpl.java
docs/source/apps/main.rst
sdk/examples/space/pom.xml
sdk/examples/space/space-to-space-supervisor/pom.xml
sdk/examples/space/space-to-space-supervisor/src/main/java/esa/mo/nmf/apps/DemoSpace2Supervisor.java
sdk/examples/space/space-to-space-supervisor/src/main/java/esa/mo/nmf/apps/Space2SupervisorAdapter.java
sdk/examples/space/space-to-space/pom.xml
sdk/examples/space/space-to-space/src/main/java/esa/mo/nmf/apps/DemoSpace2Space.java
sdk/examples/space/space-to-space/src/main/java/esa/mo/nmf/apps/Space2SpaceAdapter.java

Added two new example apps:
- app that consumes the supervisor parameter service
- app that consumes the services of another space app
Updated documentation.

Issue #1169 [examples] On-board communications

---

mission/simulator/platform-services-impl/src/test/java/esa/nmf/test/GPSSoftSimAdapterTest.java

Fix the test - improve the CRC code check.

Bug #1158 Wrong GPS TIMEA log format in simulator

---

core/mo-services-impl/ccsds-common-impl/src/main/java/esa/mo/common/impl/provider/DirectoryProviderServiceImpl.java
core/nmf-composites/generic-ground-mo-proxy/src/main/java/esa/mo/nmf/groundmoproxy/GroundMOProxy.java

This pull request contains changes fixing data duplication in the proxy when synchronizing the directory service with supervisor.

Issue #1182 Fix data duplication in Ground MO Proxy archive

---

core/nmf-composites/generic-composite-model/src/main/java/esa/mo/nmf/NMFConsumer.java
sdk/tools/consumer-test-tool/src/main/java/esa/mo/nmf/ctt/services/com/ArchiveConsumerManagerPanel.java
sdk/tools/consumer-test-tool/src/main/java/esa/mo/nmf/ctt/utils/DirectoryConnectionConsumerPanel.java
sdk/tools/consumer-test-tool/src/main/java/esa/mo/nmf/ctt/utils/LoginDialog.java
sdk/tools/consumer-test-tool/src/main/java/esa/mo/nmf/ctt/utils/ProviderTabPanel.java

This pull request contains changes allowing CTT to use login service and also connect to LWMCS.

Issue #1174 Add login service support to CTT

---

core/mo-services-impl/nmf-platform-generic-impl/src/main/java/esa/mo/platform/impl/provider/gen/GPSProviderServiceImpl.java

https://gitlab.com/esa/NMF/nmf-issues/-/issues/1188
Fix PeriodicCurrentPosition method to also update velocity
and deviation vectors.
Refactor getPosition and getPositionAndVelocity methods.

Issue #1188 [GPS Provider] Fix PeriodicCurrentPosition method

---

sdk/examples/space/camera-acquisitor-system/src/main/java/esa/mo/nmf/apps/CameraAcquisitorSystemCameraHandler.java
sdk/examples/space/camera-acquisitor-system/src/main/java/esa/mo/nmf/apps/CameraAcquisitorSystemCameraTargetHandler.java
sdk/examples/space/camera-acquisitor-system/src/main/java/esa/mo/nmf/apps/CameraAcquisitorSystemGPSHandler.java
sdk/examples/space/camera-acquisitor-system/src/main/java/esa/mo/nmf/apps/CameraAcquisitorSystemMCAdapter.java

Fix typos.
Fix latitude/longitude order.
Clean-up.

Camera Acquisitor Fixup

---

sdk/examples/ground/camera-acquisitor-system-ground/pom.xml
sdk/examples/ground/camera-acquisitor-system-ground/src/main/java/esa/mo/ground/cameraacquisotorground/CameraAcquisitorGround.java
sdk/examples/ground/camera-acquisitor-system-ground/src/main/java/esa/mo/ground/cameraacquisotorground/OrbitHandler.java
sdk/examples/ground/camera-acquisitor-system-ground/src/main/java/esa/mo/ground/restservice/Pass.java
sdk/examples/ground/camera-acquisitor-system-ground/src/main/java/esa/mo/ground/restservice/PositionAndTime.java

https://gitlab.com/esa/NMF/nmf-issues/-/issues/1162
* Fix archive recovery after app restart
* Fix typos - minor mistakes
* Add fat jar packaging in pom.xml

[Camera Acquisitor Ground] Small fixes

---

core/helper-tools/src/main/java/esa/mo/helpertools/connections/ConnectionConsumer.java
core/mo-services-impl/ccsds-com-impl/src/main/java/esa/mo/com/impl/archive/db/CallableGetCOMObjects.java
core/mo-services-impl/ccsds-com-impl/src/main/java/esa/mo/com/impl/archive/db/DatabaseBackend.java
core/mo-services-impl/ccsds-com-impl/src/main/java/esa/mo/com/impl/archive/db/PreparedStatements.java
core/nmf-composites/nmf-mo-adapters/ground-mo-adapter/src/main/java/esa/mo/nmf/groundmoadapter/GroundMOAdapterImpl.java

This pull request contains minor changes related to the MAL TCPIP transport patch. There's also one change fixing the archive when using postgresql.

Changes related to the MAL TCPIP transport patch

---

sdk/tools/consumer-test-tool/src/main/java/esa/mo/nmf/ctt/services/com/ArchiveTablePanel.java
sdk/tools/consumer-test-tool/src/main/java/esa/mo/nmf/ctt/services/com/EventConsumerPanel.java
sdk/tools/consumer-test-tool/src/main/java/esa/mo/nmf/ctt/services/sm/AppsLauncherTablePanel.java
sdk/tools/consumer-test-tool/src/main/java/esa/mo/nmf/ctt/utils/SharedTablePanel.java

This pull request contains changes allowing sorting the apps list (and other tables) in CTT

Issue #1131 Allow sorting apps list in CTT

---

core/mo-services-impl/ccsds-common-impl/src/main/java/esa/mo/common/impl/provider/ConfigurationProviderServiceImpl.java
core/mo-services-impl/ccsds-common-impl/src/main/java/esa/mo/common/impl/provider/DirectoryProviderServiceImpl.java
core/mo-services-impl/ccsds-common-impl/src/main/java/esa/mo/common/impl/util/HelperCommon.java
core/mo-services-impl/nmf-software-management-impl/src/main/java/esa/mo/sm/impl/provider/AppsLauncherProviderServiceImpl.java
core/nmf-composites/generic-composite-model/src/main/java/esa/mo/nmf/NMFConsumer.java
core/nmf-composites/generic-ground-mo-proxy/src/main/java/esa/mo/common/impl/proxy/DirectoryProxyServiceImpl.java
core/nmf-composites/generic-ground-mo-proxy/src/main/java/esa/mo/nmf/groundmoproxy/GroundMOProxy.java
core/nmf-composites/nanosat-mo-connector/src/main/java/esa/mo/nmf/nanosatmoconnector/NanoSatMOConnectorImpl.java
core/nmf-composites/nmf-mo-adapters/space-mo-adapter/src/main/java/esa/mo/nmf/spacemoadapter/SpaceMOApdapterImpl.java
parent/pom.xml
sdk/examples/ground/camera-acquisitor-system-ground/src/main/java/esa/mo/ground/cameraacquisotorground/CameraAcquisitorGround.java
sdk/examples/ground/echo/src/main/java/esa/mo/ground/echo/EchoGround.java
sdk/examples/ground/facebook/src/main/java/esa/mo/nmf/ground/facebook/Push2Facebook.java
sdk/examples/ground/set-and-command/src/main/java/esa/mo/ground/setandcommand/DemoSetAndCommand.java
sdk/examples/ground/simple-ground/src/main/java/esa/mo/ground/simpleground/SimpleGround.java
sdk/tools/com-archive-tool/src/main/java/esa/mo/nmf/comarchivetool/ArchiveBrowserHelper.java
sdk/tools/com-archive-tool/src/main/java/esa/mo/nmf/comarchivetool/CentralDirectoryHelper.java
sdk/tools/consumer-test-tool/src/main/java/esa/mo/nmf/ctt/services/common/ConfigurationConsumerPanel.java
sdk/tools/consumer-test-tool/src/main/java/esa/mo/nmf/ctt/utils/DirectoryConnectionConsumerPanel.java
sdk/tools/consumer-test-tool/src/main/java/esa/mo/nmf/ctt/utils/ProviderTabPanel.java

This pull request removes the old version of API_COMMON and replaces it with version 8.0.

Issue #1164 Update API_COMMON to version 8.0

---

core/mo-services-impl/ccsds-com-impl/src/main/java/esa/mo/com/impl/archive/db/TransactionsProcessor.java
core/mo-services-impl/ccsds-com-impl/src/main/java/esa/mo/com/impl/provider/ArchiveManager.java

Changes required for spring removal from LWMCS

Expose transactions processor for lwmcs

---

core/mo-services-impl/ccsds-com-impl/src/test/java/esa/mo/com/impl/provider/ArchiveManagerTest.java

Fast objects (Archive) unit test (manual)

Issue 1199 - Fast objects (Archive) unit test (manual)

---

core/nmf-composites/generic-composite-model/src/main/java/esa/mo/nmf/MonitorAndControlNMFAdapter.java
core/nmf-composites/nanosat-mo-supervisor/src/main/java/esa/mo/nmf/nanosatmosupervisor/MCSupervisorBasicAdapter.java
mission/simulator/opssat-spacecraft-simulator/src/main/java/opssat/simulator/celestia/CelestiaIf.java
mission/simulator/opssat-spacecraft-simulator/src/main/java/opssat/simulator/util/SimulatorHeader.java

This pull request contains changes related to LWMCS issues 311 and 310:
- fix setting values of parameters stored in obswParameterManager
- disable Celestia in supervisor simulator to prevent memory leaks

Supervisor fixes
